
package org.edu_sharing.webservices.usage;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.0-SNAPSHOT-30b8b01da0cbd72d784fbbb0710efe252293caec
 * 2022-10-11T18:45:11.363+02:00
 * Generated source version: 4.0.0-SNAPSHOT
 */

@WebFault(name = "fault1", targetNamespace = "http://usage.webservices.edu_sharing.org")
public class AuthenticationException extends Exception {

    private org.edu_sharing.webservices.authentication.AuthenticationException faultInfo;

    public AuthenticationException() {
        super();
    }

    public AuthenticationException(String message) {
        super(message);
    }

    public AuthenticationException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public AuthenticationException(String message, org.edu_sharing.webservices.authentication.AuthenticationException fault1) {
        super(message);
        this.faultInfo = fault1;
    }

    public AuthenticationException(String message, org.edu_sharing.webservices.authentication.AuthenticationException fault1, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = fault1;
    }

    public org.edu_sharing.webservices.authentication.AuthenticationException getFaultInfo() {
        return this.faultInfo;
    }
}
