
package org.edu_sharing.webservices.usage;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-04T16:42:50.682+01:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "fault1", targetNamespace = "http://usage.webservices.edu_sharing.org")
public class AuthenticationException extends Exception {

    private org.edu_sharing.webservices.authentication.AuthenticationException fault1;

    public AuthenticationException() {
        super();
    }

    public AuthenticationException(String message) {
        super(message);
    }

    public AuthenticationException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public AuthenticationException(String message, org.edu_sharing.webservices.authentication.AuthenticationException fault1) {
        super(message);
        this.fault1 = fault1;
    }

    public AuthenticationException(String message, org.edu_sharing.webservices.authentication.AuthenticationException fault1, java.lang.Throwable cause) {
        super(message, cause);
        this.fault1 = fault1;
    }

    public org.edu_sharing.webservices.authentication.AuthenticationException getFaultInfo() {
        return this.fault1;
    }
}
