
package org.edu_sharing.webservices.usage;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-01-03T11:03:55.957+01:00
 * Generated source version: 4.0.0
 */

@WebFault(name = "fault", targetNamespace = "http://usage.webservices.edu_sharing.org")
public class UsageException_Exception extends Exception {

    private org.edu_sharing.webservices.usage.UsageException faultInfo;

    public UsageException_Exception() {
        super();
    }

    public UsageException_Exception(String message) {
        super(message);
    }

    public UsageException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public UsageException_Exception(String message, org.edu_sharing.webservices.usage.UsageException fault) {
        super(message);
        this.faultInfo = fault;
    }

    public UsageException_Exception(String message, org.edu_sharing.webservices.usage.UsageException fault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = fault;
    }

    public org.edu_sharing.webservices.usage.UsageException getFaultInfo() {
        return this.faultInfo;
    }
}
