package org.edu_sharing.webservices.usage;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-01-03T11:03:55.959+01:00
 * Generated source version: 4.0.0
 *
 */
@WebServiceClient(name = "UsageService",
                  wsdlLocation = "classpath:wsdl/usage.wsdl",
                  targetNamespace = "http://usage.webservices.edu_sharing.org")
public class UsageService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://usage.webservices.edu_sharing.org", "UsageService");
    public final static QName Usage = new QName("http://usage.webservices.edu_sharing.org", "usage");
    static {
        URL url = UsageService.class.getClassLoader().getResource("wsdl/usage.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(UsageService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/usage.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UsageService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UsageService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UsageService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public UsageService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UsageService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UsageService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Usage
     */
    @WebEndpoint(name = "usage")
    public Usage getUsage() {
        return super.getPort(Usage, Usage.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Usage
     */
    @WebEndpoint(name = "usage")
    public Usage getUsage(WebServiceFeature... features) {
        return super.getPort(Usage, Usage.class, features);
    }

}
