
package org.edu_sharing.webservices.usage;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-04T16:42:50.684+01:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "fault", targetNamespace = "http://usage.webservices.edu_sharing.org")
public class UsageException_Exception extends Exception {

    private org.edu_sharing.webservices.usage.UsageException fault;

    public UsageException_Exception() {
        super();
    }

    public UsageException_Exception(String message) {
        super(message);
    }

    public UsageException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public UsageException_Exception(String message, org.edu_sharing.webservices.usage.UsageException fault) {
        super(message);
        this.fault = fault;
    }

    public UsageException_Exception(String message, org.edu_sharing.webservices.usage.UsageException fault, java.lang.Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public org.edu_sharing.webservices.usage.UsageException getFaultInfo() {
        return this.fault;
    }
}
