package org.edu_sharing.webservices.crud;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-04T16:42:50.536+01:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "CrudService",
                  wsdlLocation = "classpath:wsdl/crud.wsdl",
                  targetNamespace = "http://crud.webservices.edu_sharing.org")
public class CrudService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://crud.webservices.edu_sharing.org", "CrudService");
    public final static QName Crud = new QName("http://crud.webservices.edu_sharing.org", "crud");
    static {
        URL url = CrudService.class.getClassLoader().getResource("wsdl/crud.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(CrudService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/crud.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CrudService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CrudService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CrudService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CrudService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CrudService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CrudService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Crud
     */
    @WebEndpoint(name = "crud")
    public Crud getCrud() {
        return super.getPort(Crud, Crud.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Crud
     */
    @WebEndpoint(name = "crud")
    public Crud getCrud(WebServiceFeature... features) {
        return super.getPort(Crud, Crud.class, features);
    }

}
