package org.edu_sharing.webservices.crud;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-04T16:42:50.534+01:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://crud.webservices.edu_sharing.org", name = "Crud")
@XmlSeeAlso({org.apache.xml.xml_soap.ObjectFactory.class, ObjectFactory.class})
public interface Crud {

    @WebMethod
    @RequestWrapper(localName = "update", targetNamespace = "http://crud.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.crud.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://crud.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.crud.UpdateResponse")
    @WebResult(name = "updateReturn", targetNamespace = "http://crud.webservices.edu_sharing.org")
    public java.lang.String update(
        @WebParam(name = "username", targetNamespace = "http://crud.webservices.edu_sharing.org")
        java.lang.String username,
        @WebParam(name = "ticket", targetNamespace = "http://crud.webservices.edu_sharing.org")
        java.lang.String ticket,
        @WebParam(name = "nodeType", targetNamespace = "http://crud.webservices.edu_sharing.org")
        java.lang.String nodeType,
        @WebParam(name = "repositoryId", targetNamespace = "http://crud.webservices.edu_sharing.org")
        java.lang.String repositoryId,
        @WebParam(name = "nodeId", targetNamespace = "http://crud.webservices.edu_sharing.org")
        java.lang.String nodeId,
        @WebParam(name = "properties", targetNamespace = "http://crud.webservices.edu_sharing.org")
        org.apache.xml.xml_soap.Map properties,
        @WebParam(name = "content", targetNamespace = "http://crud.webservices.edu_sharing.org")
        byte[] content,
        @WebParam(name = "icon", targetNamespace = "http://crud.webservices.edu_sharing.org")
        byte[] icon
    );

    @WebMethod
    @RequestWrapper(localName = "create", targetNamespace = "http://crud.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.crud.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://crud.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.crud.CreateResponse")
    @WebResult(name = "createReturn", targetNamespace = "http://crud.webservices.edu_sharing.org")
    public java.lang.String create(
        @WebParam(name = "username", targetNamespace = "http://crud.webservices.edu_sharing.org")
        java.lang.String username,
        @WebParam(name = "ticket", targetNamespace = "http://crud.webservices.edu_sharing.org")
        java.lang.String ticket,
        @WebParam(name = "nodeType", targetNamespace = "http://crud.webservices.edu_sharing.org")
        java.lang.String nodeType,
        @WebParam(name = "repositoryId", targetNamespace = "http://crud.webservices.edu_sharing.org")
        java.lang.String repositoryId,
        @WebParam(name = "properties", targetNamespace = "http://crud.webservices.edu_sharing.org")
        org.apache.xml.xml_soap.Map properties,
        @WebParam(name = "content", targetNamespace = "http://crud.webservices.edu_sharing.org")
        byte[] content,
        @WebParam(name = "icon", targetNamespace = "http://crud.webservices.edu_sharing.org")
        byte[] icon
    );
}
