package org.edu_sharing.webservices.authbyapp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-04T16:42:50.419+01:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://authbyapp.webservices.edu_sharing.org", name = "AuthByApp")
@XmlSeeAlso({ObjectFactory.class, org.edu_sharing.webservices.types.ObjectFactory.class, org.edu_sharing.webservices.authentication.ObjectFactory.class})
public interface AuthByApp {

    @WebMethod
    @RequestWrapper(localName = "checkTicket", targetNamespace = "http://authbyapp.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.authbyapp.CheckTicket")
    @ResponseWrapper(localName = "checkTicketResponse", targetNamespace = "http://authbyapp.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.authbyapp.CheckTicketResponse")
    @WebResult(name = "checkTicketReturn", targetNamespace = "http://authbyapp.webservices.edu_sharing.org")
    public boolean checkTicket(
        @WebParam(name = "ticket", targetNamespace = "http://authbyapp.webservices.edu_sharing.org")
        java.lang.String ticket
    ) throws AuthenticationException;

    @WebMethod
    @RequestWrapper(localName = "authenticateByTrustedApp", targetNamespace = "http://authbyapp.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.authbyapp.AuthenticateByTrustedApp")
    @ResponseWrapper(localName = "authenticateByTrustedAppResponse", targetNamespace = "http://authbyapp.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.authbyapp.AuthenticateByTrustedAppResponse")
    @WebResult(name = "authenticateByTrustedAppReturn", targetNamespace = "http://authbyapp.webservices.edu_sharing.org")
    public org.edu_sharing.webservices.authentication.AuthenticationResult authenticateByTrustedApp(
        @WebParam(name = "applicationId", targetNamespace = "http://authbyapp.webservices.edu_sharing.org")
        java.lang.String applicationId,
        @WebParam(name = "ssoData", targetNamespace = "http://authbyapp.webservices.edu_sharing.org")
        java.util.List<org.edu_sharing.webservices.types.KeyValue> ssoData
    ) throws AuthenticationException;
}
