
package org.edu_sharing.webservices.authbyapp;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-04T16:42:50.417+01:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "fault", targetNamespace = "http://authbyapp.webservices.edu_sharing.org")
public class AuthenticationException extends Exception {

    private org.edu_sharing.webservices.authentication.AuthenticationException fault;

    public AuthenticationException() {
        super();
    }

    public AuthenticationException(String message) {
        super(message);
    }

    public AuthenticationException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public AuthenticationException(String message, org.edu_sharing.webservices.authentication.AuthenticationException fault) {
        super(message);
        this.fault = fault;
    }

    public AuthenticationException(String message, org.edu_sharing.webservices.authentication.AuthenticationException fault, java.lang.Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public org.edu_sharing.webservices.authentication.AuthenticationException getFaultInfo() {
        return this.fault;
    }
}
