
package org.edu_sharing.webservices.authbyapp;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-01-03T11:03:55.821+01:00
 * Generated source version: 4.0.0
 */

@WebFault(name = "fault", targetNamespace = "http://authbyapp.webservices.edu_sharing.org")
public class AuthenticationException extends Exception {

    private org.edu_sharing.webservices.authentication.AuthenticationException faultInfo;

    public AuthenticationException() {
        super();
    }

    public AuthenticationException(String message) {
        super(message);
    }

    public AuthenticationException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public AuthenticationException(String message, org.edu_sharing.webservices.authentication.AuthenticationException fault) {
        super(message);
        this.faultInfo = fault;
    }

    public AuthenticationException(String message, org.edu_sharing.webservices.authentication.AuthenticationException fault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = fault;
    }

    public org.edu_sharing.webservices.authentication.AuthenticationException getFaultInfo() {
        return this.faultInfo;
    }
}
