package org.edu_sharing.webservices.authbyapp;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.0-SNAPSHOT-30b8b01da0cbd72d784fbbb0710efe252293caec
 * 2022-10-11T18:45:11.209+02:00
 * Generated source version: 4.0.0-SNAPSHOT
 *
 */
@WebServiceClient(name = "AuthByAppService",
                  wsdlLocation = "classpath:wsdl/authbyapp.wsdl",
                  targetNamespace = "http://authbyapp.webservices.edu_sharing.org")
public class AuthByAppService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://authbyapp.webservices.edu_sharing.org", "AuthByAppService");
    public final static QName Authbyapp = new QName("http://authbyapp.webservices.edu_sharing.org", "authbyapp");
    static {
        URL url = AuthByAppService.class.getClassLoader().getResource("wsdl/authbyapp.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(AuthByAppService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/authbyapp.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AuthByAppService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AuthByAppService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthByAppService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AuthByAppService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AuthByAppService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AuthByAppService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns AuthByApp
     */
    @WebEndpoint(name = "authbyapp")
    public AuthByApp getAuthbyapp() {
        return super.getPort(Authbyapp, AuthByApp.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthByApp
     */
    @WebEndpoint(name = "authbyapp")
    public AuthByApp getAuthbyapp(WebServiceFeature... features) {
        return super.getPort(Authbyapp, AuthByApp.class, features);
    }

}
