package org.edu_sharing.webservices.authbyapp;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.0-SNAPSHOT-30b8b01da0cbd72d784fbbb0710efe252293caec
 * 2022-10-11T18:45:11.208+02:00
 * Generated source version: 4.0.0-SNAPSHOT
 *
 */
@WebService(targetNamespace = "http://authbyapp.webservices.edu_sharing.org", name = "AuthByApp")
@XmlSeeAlso({ObjectFactory.class, org.edu_sharing.webservices.types.ObjectFactory.class, org.edu_sharing.webservices.authentication.ObjectFactory.class})
public interface AuthByApp {

    @WebMethod
    @RequestWrapper(localName = "checkTicket", targetNamespace = "http://authbyapp.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.authbyapp.CheckTicket")
    @ResponseWrapper(localName = "checkTicketResponse", targetNamespace = "http://authbyapp.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.authbyapp.CheckTicketResponse")
    @WebResult(name = "checkTicketReturn", targetNamespace = "http://authbyapp.webservices.edu_sharing.org")
    public boolean checkTicket(

        @WebParam(name = "ticket", targetNamespace = "http://authbyapp.webservices.edu_sharing.org")
        java.lang.String ticket
    ) throws AuthenticationException;

    @WebMethod
    @RequestWrapper(localName = "authenticateByTrustedApp", targetNamespace = "http://authbyapp.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.authbyapp.AuthenticateByTrustedApp")
    @ResponseWrapper(localName = "authenticateByTrustedAppResponse", targetNamespace = "http://authbyapp.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.authbyapp.AuthenticateByTrustedAppResponse")
    @WebResult(name = "authenticateByTrustedAppReturn", targetNamespace = "http://authbyapp.webservices.edu_sharing.org")
    public org.edu_sharing.webservices.authentication.AuthenticationResult authenticateByTrustedApp(

        @WebParam(name = "applicationId", targetNamespace = "http://authbyapp.webservices.edu_sharing.org")
        java.lang.String applicationId,
        @WebParam(name = "ssoData", targetNamespace = "http://authbyapp.webservices.edu_sharing.org")
        java.util.List<org.edu_sharing.webservices.types.KeyValue> ssoData
    ) throws AuthenticationException;
}
