package org.edu_sharing.webservices.permission;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-04T16:42:50.574+01:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "PermissionService",
                  wsdlLocation = "classpath:wsdl/permission.wsdl",
                  targetNamespace = "http://permission.webservices.edu_sharing.org")
public class PermissionService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://permission.webservices.edu_sharing.org", "PermissionService");
    public final static QName Permission = new QName("http://permission.webservices.edu_sharing.org", "permission");
    static {
        URL url = PermissionService.class.getClassLoader().getResource("wsdl/permission.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(PermissionService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/permission.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PermissionService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PermissionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PermissionService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public PermissionService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PermissionService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PermissionService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Permission
     */
    @WebEndpoint(name = "permission")
    public Permission getPermission() {
        return super.getPort(Permission, Permission.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Permission
     */
    @WebEndpoint(name = "permission")
    public Permission getPermission(WebServiceFeature... features) {
        return super.getPort(Permission, Permission.class, features);
    }

}
