package org.edu_sharing.webservices.render;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-01-03T11:03:55.763+01:00
 * Generated source version: 4.0.0
 *
 */
@WebService(targetNamespace = "http://render.webservices.edu_sharing.org", name = "RenderInfo")
@XmlSeeAlso({org.edu_sharing.webservices.types.ObjectFactory.class, org.edu_sharing.webservices.usage.ObjectFactory.class, ObjectFactory.class})
public interface RenderInfo {

    @WebMethod
    @RequestWrapper(localName = "getRenderInfoRepo", targetNamespace = "http://render.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.render.GetRenderInfoRepo")
    @ResponseWrapper(localName = "getRenderInfoRepoResponse", targetNamespace = "http://render.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.render.GetRenderInfoRepoResponse")
    @WebResult(name = "getRenderInfoRepoReturn", targetNamespace = "http://render.webservices.edu_sharing.org")
    public org.edu_sharing.webservices.render.RenderInfoResult getRenderInfoRepo(

        @WebParam(name = "userName", targetNamespace = "http://render.webservices.edu_sharing.org")
        java.lang.String userName,
        @WebParam(name = "nodeId", targetNamespace = "http://render.webservices.edu_sharing.org")
        java.lang.String nodeId,
        @WebParam(name = "version", targetNamespace = "http://render.webservices.edu_sharing.org")
        java.lang.String version
    );

    @WebMethod
    @RequestWrapper(localName = "getRenderInfoLMS", targetNamespace = "http://render.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.render.GetRenderInfoLMS")
    @ResponseWrapper(localName = "getRenderInfoLMSResponse", targetNamespace = "http://render.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.render.GetRenderInfoLMSResponse")
    @WebResult(name = "getRenderInfoLMSReturn", targetNamespace = "http://render.webservices.edu_sharing.org")
    public org.edu_sharing.webservices.render.RenderInfoResult getRenderInfoLMS(

        @WebParam(name = "userName", targetNamespace = "http://render.webservices.edu_sharing.org")
        java.lang.String userName,
        @WebParam(name = "nodeId", targetNamespace = "http://render.webservices.edu_sharing.org")
        java.lang.String nodeId,
        @WebParam(name = "lmsId", targetNamespace = "http://render.webservices.edu_sharing.org")
        java.lang.String lmsId,
        @WebParam(name = "courseId", targetNamespace = "http://render.webservices.edu_sharing.org")
        java.lang.String courseId,
        @WebParam(name = "resourceId", targetNamespace = "http://render.webservices.edu_sharing.org")
        java.lang.String resourceId,
        @WebParam(name = "version", targetNamespace = "http://render.webservices.edu_sharing.org")
        java.lang.String version
    );
}
