
package org.edu_sharing.webservices.usage2;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-01-03T11:03:55.981+01:00
 * Generated source version: 4.0.0
 */

@WebFault(name = "fault", targetNamespace = "http://usage2.webservices.edu_sharing.org")
public class Usage2Exception_Exception extends Exception {

    private org.edu_sharing.webservices.usage2.Usage2Exception faultInfo;

    public Usage2Exception_Exception() {
        super();
    }

    public Usage2Exception_Exception(String message) {
        super(message);
    }

    public Usage2Exception_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public Usage2Exception_Exception(String message, org.edu_sharing.webservices.usage2.Usage2Exception fault) {
        super(message);
        this.faultInfo = fault;
    }

    public Usage2Exception_Exception(String message, org.edu_sharing.webservices.usage2.Usage2Exception fault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = fault;
    }

    public org.edu_sharing.webservices.usage2.Usage2Exception getFaultInfo() {
        return this.faultInfo;
    }
}
