
package org.edu_sharing.webservices.usage2;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 4.0.0-SNAPSHOT-30b8b01da0cbd72d784fbbb0710efe252293caec
 * 2022-10-11T18:45:11.395+02:00
 * Generated source version: 4.0.0-SNAPSHOT
 *
 */
public final class Usage2_Usage2_Client {

    private static final QName SERVICE_NAME = new QName("http://usage2.webservices.edu_sharing.org", "Usage2Service");

    private Usage2_Usage2_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Usage2Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        Usage2Service ss = new Usage2Service(wsdlURL, SERVICE_NAME);
        Usage2 port = ss.getUsage2();

        {
        System.out.println("Invoking getUsagesByEduRef...");
        java.lang.String _getUsagesByEduRef_eduRef = "";
        java.lang.String _getUsagesByEduRef_user = "";
        try {
            java.util.List<org.edu_sharing.webservices.usage2.Usage2Result> _getUsagesByEduRef__return = port.getUsagesByEduRef(_getUsagesByEduRef_eduRef, _getUsagesByEduRef_user);
            System.out.println("getUsagesByEduRef.result=" + _getUsagesByEduRef__return);

        } catch (Usage2Exception_Exception e) {
            System.out.println("Expected exception: Usage2Exception has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking setUsage...");
        java.lang.String _setUsage_eduRef = "";
        java.lang.String _setUsage_user = "";
        java.lang.String _setUsage_lmsId = "";
        java.lang.String _setUsage_courseId = "";
        java.lang.String _setUsage_userMail = "";
        javax.xml.datatype.XMLGregorianCalendar _setUsage_fromUsed = null;
        javax.xml.datatype.XMLGregorianCalendar _setUsage_toUsed = null;
        int _setUsage_distinctPersons = 0;
        java.lang.String _setUsage_version = "";
        java.lang.String _setUsage_resourceId = "";
        java.lang.String _setUsage_xmlParams = "";
        try {
            org.edu_sharing.webservices.usage2.Usage2Result _setUsage__return = port.setUsage(_setUsage_eduRef, _setUsage_user, _setUsage_lmsId, _setUsage_courseId, _setUsage_userMail, _setUsage_fromUsed, _setUsage_toUsed, _setUsage_distinctPersons, _setUsage_version, _setUsage_resourceId, _setUsage_xmlParams);
            System.out.println("setUsage.result=" + _setUsage__return);

        } catch (Usage2Exception_Exception e) {
            System.out.println("Expected exception: Usage2Exception has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getUsage...");
        java.lang.String _getUsage_eduRef = "";
        java.lang.String _getUsage_lmsId = "";
        java.lang.String _getUsage_courseId = "";
        java.lang.String _getUsage_user = "";
        java.lang.String _getUsage_resourceId = "";
        try {
            org.edu_sharing.webservices.usage2.Usage2Result _getUsage__return = port.getUsage(_getUsage_eduRef, _getUsage_lmsId, _getUsage_courseId, _getUsage_user, _getUsage_resourceId);
            System.out.println("getUsage.result=" + _getUsage__return);

        } catch (Usage2Exception_Exception e) {
            System.out.println("Expected exception: Usage2Exception has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking deleteUsage...");
        java.lang.String _deleteUsage_eduRef = "";
        java.lang.String _deleteUsage_user = "";
        java.lang.String _deleteUsage_lmsId = "";
        java.lang.String _deleteUsage_courseId = "";
        java.lang.String _deleteUsage_resourceId = "";
        try {
            boolean _deleteUsage__return = port.deleteUsage(_deleteUsage_eduRef, _deleteUsage_user, _deleteUsage_lmsId, _deleteUsage_courseId, _deleteUsage_resourceId);
            System.out.println("deleteUsage.result=" + _deleteUsage__return);

        } catch (Usage2Exception_Exception e) {
            System.out.println("Expected exception: Usage2Exception has occurred.");
            System.out.println(e.toString());
        }

            }

        System.exit(0);
    }

}
