
package org.edu_sharing.webservices.usage2;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-04T16:42:50.735+01:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "fault", targetNamespace = "http://usage2.webservices.edu_sharing.org")
public class Usage2Exception_Exception extends Exception {

    private org.edu_sharing.webservices.usage2.Usage2Exception fault;

    public Usage2Exception_Exception() {
        super();
    }

    public Usage2Exception_Exception(String message) {
        super(message);
    }

    public Usage2Exception_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public Usage2Exception_Exception(String message, org.edu_sharing.webservices.usage2.Usage2Exception fault) {
        super(message);
        this.fault = fault;
    }

    public Usage2Exception_Exception(String message, org.edu_sharing.webservices.usage2.Usage2Exception fault, java.lang.Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public org.edu_sharing.webservices.usage2.Usage2Exception getFaultInfo() {
        return this.fault;
    }
}
