package org.edu_sharing.webservices.authentication;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.0-SNAPSHOT-30b8b01da0cbd72d784fbbb0710efe252293caec
 * 2022-10-11T18:45:11.244+02:00
 * Generated source version: 4.0.0-SNAPSHOT
 *
 */
@WebServiceClient(name = "AuthenticationService",
                  wsdlLocation = "classpath:wsdl/authentication.wsdl",
                  targetNamespace = "http://authentication.webservices.edu_sharing.org")
public class AuthenticationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://authentication.webservices.edu_sharing.org", "AuthenticationService");
    public final static QName Authentication = new QName("http://authentication.webservices.edu_sharing.org", "authentication");
    static {
        URL url = AuthenticationService.class.getClassLoader().getResource("wsdl/authentication.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(AuthenticationService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/authentication.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AuthenticationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AuthenticationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthenticationService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AuthenticationService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AuthenticationService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AuthenticationService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Authentication
     */
    @WebEndpoint(name = "authentication")
    public Authentication getAuthentication() {
        return super.getPort(Authentication, Authentication.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Authentication
     */
    @WebEndpoint(name = "authentication")
    public Authentication getAuthentication(WebServiceFeature... features) {
        return super.getPort(Authentication, Authentication.class, features);
    }

}
