
package org.edu_sharing.webservices.authentication;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.0-SNAPSHOT-30b8b01da0cbd72d784fbbb0710efe252293caec
 * 2022-10-11T18:45:11.241+02:00
 * Generated source version: 4.0.0-SNAPSHOT
 */

@WebFault(name = "fault", targetNamespace = "http://authentication.webservices.edu_sharing.org")
public class AuthenticationException_Exception extends Exception {

    private org.edu_sharing.webservices.authentication.AuthenticationException faultInfo;

    public AuthenticationException_Exception() {
        super();
    }

    public AuthenticationException_Exception(String message) {
        super(message);
    }

    public AuthenticationException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public AuthenticationException_Exception(String message, org.edu_sharing.webservices.authentication.AuthenticationException fault) {
        super(message);
        this.faultInfo = fault;
    }

    public AuthenticationException_Exception(String message, org.edu_sharing.webservices.authentication.AuthenticationException fault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = fault;
    }

    public org.edu_sharing.webservices.authentication.AuthenticationException getFaultInfo() {
        return this.faultInfo;
    }
}
