package org.edu_sharing.webservices.foldertemplate;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-01-03T11:03:55.400+01:00
 * Generated source version: 4.0.0
 *
 */
@WebService(targetNamespace = "http://foldertemplate.webservices.edu_sharing.org", name = "FolderTemplate")
@XmlSeeAlso({ObjectFactory.class})
public interface FolderTemplate {

    @WebMethod
    @RequestWrapper(localName = "process", targetNamespace = "http://foldertemplate.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.foldertemplate.Process")
    @ResponseWrapper(localName = "processResponse", targetNamespace = "http://foldertemplate.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.foldertemplate.ProcessResponse")
    @WebResult(name = "processReturn", targetNamespace = "http://foldertemplate.webservices.edu_sharing.org")
    public java.lang.String process(

        @WebParam(name = "template", targetNamespace = "http://foldertemplate.webservices.edu_sharing.org")
        java.lang.String template,
        @WebParam(name = "group", targetNamespace = "http://foldertemplate.webservices.edu_sharing.org")
        java.lang.String group,
        @WebParam(name = "folderid", targetNamespace = "http://foldertemplate.webservices.edu_sharing.org")
        java.lang.String folderid
    );
}
