
package org.edu_sharing.webservices.foldertemplate;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 4.0.0-SNAPSHOT-30b8b01da0cbd72d784fbbb0710efe252293caec
 * 2022-10-11T18:45:10.683+02:00
 * Generated source version: 4.0.0-SNAPSHOT
 *
 */
public final class FolderTemplate_FolderTemplate_Client {

    private static final QName SERVICE_NAME = new QName("http://foldertemplate.webservices.edu_sharing.org", "FolderTemplateService");

    private FolderTemplate_FolderTemplate_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = FolderTemplateService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        FolderTemplateService ss = new FolderTemplateService(wsdlURL, SERVICE_NAME);
        FolderTemplate port = ss.getFolderTemplate();

        {
        System.out.println("Invoking process...");
        java.lang.String _process_template = "";
        java.lang.String _process_group = "";
        java.lang.String _process_folderid = "";
        java.lang.String _process__return = port.process(_process_template, _process_group, _process_folderid);
        System.out.println("process.result=" + _process__return);


        }

        System.exit(0);
    }

}
