package org.edu_sharing.webservices.alfresco.extension;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-01-03T11:03:55.727+01:00
 * Generated source version: 4.0.0
 *
 */
@WebServiceClient(name = "NativeAlfrescoWrapperService",
                  wsdlLocation = "classpath:wsdl/NativeAlfrescoWrapper.wsdl",
                  targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
public class NativeAlfrescoWrapperService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://extension.alfresco.webservices.edu_sharing.org", "NativeAlfrescoWrapperService");
    public final static QName NativeAlfrescoWrapper = new QName("http://extension.alfresco.webservices.edu_sharing.org", "NativeAlfrescoWrapper");
    static {
        URL url = NativeAlfrescoWrapperService.class.getClassLoader().getResource("wsdl/NativeAlfrescoWrapper.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(NativeAlfrescoWrapperService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/NativeAlfrescoWrapper.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public NativeAlfrescoWrapperService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NativeAlfrescoWrapperService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NativeAlfrescoWrapperService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public NativeAlfrescoWrapperService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public NativeAlfrescoWrapperService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public NativeAlfrescoWrapperService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns NativeAlfrescoWrapper
     */
    @WebEndpoint(name = "NativeAlfrescoWrapper")
    public NativeAlfrescoWrapper getNativeAlfrescoWrapper() {
        return super.getPort(NativeAlfrescoWrapper, NativeAlfrescoWrapper.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NativeAlfrescoWrapper
     */
    @WebEndpoint(name = "NativeAlfrescoWrapper")
    public NativeAlfrescoWrapper getNativeAlfrescoWrapper(WebServiceFeature... features) {
        return super.getPort(NativeAlfrescoWrapper, NativeAlfrescoWrapper.class, features);
    }

}
