package org.edu_sharing.webservices.alfresco.extension;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.0-SNAPSHOT-30b8b01da0cbd72d784fbbb0710efe252293caec
 * 2022-10-11T18:45:11.092+02:00
 * Generated source version: 4.0.0-SNAPSHOT
 *
 */
@WebService(targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", name = "NativeAlfrescoWrapper")
@XmlSeeAlso({org.edu_sharing.repository.client.rpc.ObjectFactory.class, org.apache.xml.xml_soap.ObjectFactory.class, ObjectFactory.class})
public interface NativeAlfrescoWrapper {

    @WebMethod
    @RequestWrapper(localName = "isOwner", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.IsOwner")
    @ResponseWrapper(localName = "isOwnerResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.IsOwnerResponse")
    @WebResult(name = "isOwnerReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public boolean isOwner(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId,
        @WebParam(name = "user", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String user
    );

    @WebMethod
    @RequestWrapper(localName = "bindEduGroupFolder", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.BindEduGroupFolder")
    @ResponseWrapper(localName = "bindEduGroupFolderResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.BindEduGroupFolderResponse")
    public void bindEduGroupFolder(

        @WebParam(name = "groupName", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String groupName,
        @WebParam(name = "folderId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String folderId
    );

    @WebMethod
    @RequestWrapper(localName = "setUserDefinedPreview", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.SetUserDefinedPreview")
    @ResponseWrapper(localName = "setUserDefinedPreviewResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.SetUserDefinedPreviewResponse")
    public void setUserDefinedPreview(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId,
        @WebParam(name = "content", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        byte[] content,
        @WebParam(name = "fileName", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String fileName
    );

    @WebMethod
    @RequestWrapper(localName = "getHomeFolderID", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetHomeFolderID")
    @ResponseWrapper(localName = "getHomeFolderIDResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetHomeFolderIDResponse")
    @WebResult(name = "getHomeFolderIDReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public java.lang.String getHomeFolderID(

        @WebParam(name = "username", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String username
    );

    @WebMethod
    @RequestWrapper(localName = "addAspect", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.AddAspect")
    @ResponseWrapper(localName = "addAspectResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.AddAspectResponse")
    public void addAspect(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId,
        @WebParam(name = "aspect", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String aspect
    );

    @WebMethod
    @RequestWrapper(localName = "getPath", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetPath")
    @ResponseWrapper(localName = "getPathResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetPathResponse")
    @WebResult(name = "getPathReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public java.lang.String getPath(

        @WebParam(name = "nodeID", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeID
    );

    @WebMethod
    @RequestWrapper(localName = "getChildenByProps", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetChildenByProps")
    @ResponseWrapper(localName = "getChildenByPropsResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetChildenByPropsResponse")
    @WebResult(name = "getChildenByPropsReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public org.apache.xml.xml_soap.Map getChildenByProps(

        @WebParam(name = "parentId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String parentId,
        @WebParam(name = "type", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String type,
        @WebParam(name = "props", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        org.apache.xml.xml_soap.Map props
    );

    @WebMethod
    @RequestWrapper(localName = "getPropertiesExt", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetPropertiesExt")
    @ResponseWrapper(localName = "getPropertiesExtResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetPropertiesExtResponse")
    @WebResult(name = "getPropertiesExtReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public org.apache.xml.xml_soap.Map getPropertiesExt(

        @WebParam(name = "storeProtocol", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String storeProtocol,
        @WebParam(name = "storeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String storeId,
        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId
    );

    @WebMethod
    @RequestWrapper(localName = "getChildrenRecursive", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetChildrenRecursive")
    @ResponseWrapper(localName = "getChildrenRecursiveResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetChildrenRecursiveResponse")
    @WebResult(name = "getChildrenRecursiveReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public org.apache.xml.xml_soap.Map getChildrenRecursive(

        @WebParam(name = "parentId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String parentId,
        @WebParam(name = "type", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String type
    );

    @WebMethod
    @RequestWrapper(localName = "setGroupDetails", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.SetGroupDetails")
    @ResponseWrapper(localName = "setGroupDetailsResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.SetGroupDetailsResponse")
    @WebResult(name = "setGroupDetailsReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public org.edu_sharing.webservices.alfresco.extension.GroupDetails setGroupDetails(

        @WebParam(name = "groupDetails", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        org.edu_sharing.webservices.alfresco.extension.GroupDetails groupDetails
    );

    @WebMethod
    @RequestWrapper(localName = "updateNodeAtomicValues", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.UpdateNodeAtomicValues")
    @ResponseWrapper(localName = "updateNodeAtomicValuesResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.UpdateNodeAtomicValuesResponse")
    public void updateNodeAtomicValues(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId,
        @WebParam(name = "properties", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        org.apache.xml.xml_soap.Map properties
    );

    @WebMethod
    @RequestWrapper(localName = "setPermissionsBasic", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.SetPermissionsBasic")
    @ResponseWrapper(localName = "setPermissionsBasicResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.SetPermissionsBasicResponse")
    public void setPermissionsBasic(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId,
        @WebParam(name = "_authority", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String authority,
        @WebParam(name = "permissions", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.util.List<java.lang.String> permissions,
        @WebParam(name = "changeInherit", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        boolean changeInherit,
        @WebParam(name = "inheritPermission", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        boolean inheritPermission
    );

    @WebMethod
    @RequestWrapper(localName = "createNode", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.CreateNode")
    @ResponseWrapper(localName = "createNodeResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.CreateNodeResponse")
    @WebResult(name = "createNodeReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public java.lang.String createNode(

        @WebParam(name = "parentID", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String parentID,
        @WebParam(name = "nodeTypeString", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeTypeString,
        @WebParam(name = "childAssociation", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String childAssociation,
        @WebParam(name = "props", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        org.apache.xml.xml_soap.Map props
    );

    @WebMethod
    @RequestWrapper(localName = "hasAllPermissions", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.HasAllPermissions")
    @ResponseWrapper(localName = "hasAllPermissionsResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.HasAllPermissionsResponse")
    @WebResult(name = "hasAllPermissionsReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public org.apache.xml.xml_soap.Map hasAllPermissions(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId,
        @WebParam(name = "permissions", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.util.List<java.lang.String> permissions
    );

    @WebMethod
    @RequestWrapper(localName = "removePermissionACEs", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.RemovePermissionACEs")
    @ResponseWrapper(localName = "removePermissionACEsResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.RemovePermissionACEsResponse")
    public void removePermissionACEs(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId,
        @WebParam(name = "aces", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.util.List<org.edu_sharing.repository.client.rpc.ACE> aces
    );

    @WebMethod
    @RequestWrapper(localName = "createAssociation", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.CreateAssociation")
    @ResponseWrapper(localName = "createAssociationResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.CreateAssociationResponse")
    public void createAssociation(

        @WebParam(name = "fromID", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String fromID,
        @WebParam(name = "toID", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String toID,
        @WebParam(name = "association", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String association
    );

    @WebMethod
    @RequestWrapper(localName = "hasPermissions", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.HasPermissions")
    @ResponseWrapper(localName = "hasPermissionsResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.HasPermissionsResponse")
    @WebResult(name = "hasPermissionsReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public org.apache.xml.xml_soap.Map hasPermissions(

        @WebParam(name = "userId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String userId,
        @WebParam(name = "permissions", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.util.List<java.lang.String> permissions,
        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId
    );

    @WebMethod
    @RequestWrapper(localName = "searchNodes", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.SearchNodes")
    @ResponseWrapper(localName = "searchNodesResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.SearchNodesResponse")
    @WebResult(name = "searchNodesReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public java.util.List<org.edu_sharing.webservices.alfresco.extension.RepositoryNode> searchNodes(

        @WebParam(name = "store", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String store,
        @WebParam(name = "luceneQuery", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String luceneQuery,
        @WebParam(name = "permission", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String permission,
        @WebParam(name = "propertiesToReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.util.List<java.lang.String> propertiesToReturn
    );

    @WebMethod
    @RequestWrapper(localName = "removeUserDefinedPreview", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.RemoveUserDefinedPreview")
    @ResponseWrapper(localName = "removeUserDefinedPreviewResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.RemoveUserDefinedPreviewResponse")
    public void removeUserDefinedPreview(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId
    );

    @WebMethod
    @RequestWrapper(localName = "searchSolr", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.SearchSolr")
    @ResponseWrapper(localName = "searchSolrResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.SearchSolrResponse")
    @WebResult(name = "searchSolrReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public org.edu_sharing.webservices.alfresco.extension.SearchResult searchSolr(

        @WebParam(name = "query", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String query,
        @WebParam(name = "startIdx", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        int startIdx,
        @WebParam(name = "nrOfresults", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        int nrOfresults,
        @WebParam(name = "facettes", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.util.List<java.lang.String> facettes,
        @WebParam(name = "facettesMinCount", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        int facettesMinCount,
        @WebParam(name = "facettesLimit", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        int facettesLimit
    );

    @WebMethod
    @RequestWrapper(localName = "setPermissions", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.SetPermissions")
    @ResponseWrapper(localName = "setPermissionsResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.SetPermissionsResponse")
    public void setPermissions(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId,
        @WebParam(name = "aces", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.util.List<org.edu_sharing.repository.client.rpc.ACE> aces
    );

    @WebMethod
    @RequestWrapper(localName = "searchNodeIdsLimit", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.SearchNodeIdsLimit")
    @ResponseWrapper(localName = "searchNodeIdsLimitResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.SearchNodeIdsLimitResponse")
    @WebResult(name = "searchNodeIdsLimitReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public java.util.List<java.lang.String> searchNodeIdsLimit(

        @WebParam(name = "luceneString", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String luceneString,
        @WebParam(name = "limit", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        int limit
    );

    @WebMethod
    @RequestWrapper(localName = "setOwner", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.SetOwner")
    @ResponseWrapper(localName = "setOwnerResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.SetOwnerResponse")
    public void setOwner(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId,
        @WebParam(name = "username", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String username
    );

    @WebMethod
    @RequestWrapper(localName = "removeChild", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.RemoveChild")
    @ResponseWrapper(localName = "removeChildResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.RemoveChildResponse")
    public void removeChild(

        @WebParam(name = "parentID", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String parentID,
        @WebParam(name = "childID", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String childID,
        @WebParam(name = "association", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String association
    );

    @WebMethod
    @RequestWrapper(localName = "invalideTicket", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.InvalideTicket")
    @ResponseWrapper(localName = "invalideTicketResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.InvalideTicketResponse")
    public void invalideTicket(

        @WebParam(name = "ticket", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String ticket
    );

    @WebMethod
    @RequestWrapper(localName = "removeRelations", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.RemoveRelations")
    @ResponseWrapper(localName = "removeRelationsResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.RemoveRelationsResponse")
    public void removeRelations(

        @WebParam(name = "parentID", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String parentID
    );

    @WebMethod
    @RequestWrapper(localName = "getType", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetType")
    @ResponseWrapper(localName = "getTypeResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetTypeResponse")
    @WebResult(name = "getTypeReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public java.lang.String getType(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId
    );

    @WebMethod
    @RequestWrapper(localName = "getUserNames", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetUserNames")
    @ResponseWrapper(localName = "getUserNamesResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetUserNamesResponse")
    @WebResult(name = "getUserNamesReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public java.util.List<java.lang.String> getUserNames()
;

    @WebMethod
    @RequestWrapper(localName = "setProperty", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.SetProperty")
    @ResponseWrapper(localName = "setPropertyResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.SetPropertyResponse")
    public void setProperty(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId,
        @WebParam(name = "property", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String property,
        @WebParam(name = "value", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String value
    );

    @WebMethod
    @RequestWrapper(localName = "moveNode", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.MoveNode")
    @ResponseWrapper(localName = "moveNodeResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.MoveNodeResponse")
    public void moveNode(

        @WebParam(name = "newParentId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String newParentId,
        @WebParam(name = "childAssocType", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String childAssocType,
        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId
    );

    @WebMethod
    @RequestWrapper(localName = "getNotifyList", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetNotifyList")
    @ResponseWrapper(localName = "getNotifyListResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetNotifyListResponse")
    @WebResult(name = "getNotifyListReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public java.util.List<org.edu_sharing.repository.client.rpc.Notify> getNotifyList(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId
    );

    @WebMethod
    @RequestWrapper(localName = "getChildren", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetChildren")
    @ResponseWrapper(localName = "getChildrenResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetChildrenResponse")
    @WebResult(name = "getChildrenReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public org.apache.xml.xml_soap.Map getChildren(

        @WebParam(name = "parentID", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String parentID,
        @WebParam(name = "type", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String type
    );

    @WebMethod
    @RequestWrapper(localName = "updateNode", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.UpdateNode")
    @ResponseWrapper(localName = "updateNodeResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.UpdateNodeResponse")
    public void updateNode(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId,
        @WebParam(name = "properties", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        org.apache.xml.xml_soap.Map properties
    );

    @WebMethod
    @RequestWrapper(localName = "getMetadataSets", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetMetadataSets")
    @ResponseWrapper(localName = "getMetadataSetsResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetMetadataSetsResponse")
    @WebResult(name = "getMetadataSetsReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public java.util.List<java.lang.String> getMetadataSets()
;

    @WebMethod
    @RequestWrapper(localName = "getPropertiesSimple", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetPropertiesSimple")
    @ResponseWrapper(localName = "getPropertiesSimpleResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetPropertiesSimpleResponse")
    @WebResult(name = "getPropertiesSimpleReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public org.apache.xml.xml_soap.Map getPropertiesSimple(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId
    );

    @WebMethod
    @RequestWrapper(localName = "getPreviewUrl", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetPreviewUrl")
    @ResponseWrapper(localName = "getPreviewUrlResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetPreviewUrlResponse")
    @WebResult(name = "getPreviewUrlReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public org.edu_sharing.repository.client.rpc.GetPreviewResult getPreviewUrl(

        @WebParam(name = "storeProtocol", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String storeProtocol,
        @WebParam(name = "storeIdentifier", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String storeIdentifier,
        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId
    );

    @WebMethod
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.DeleteUserResponse")
    public void deleteUser(

        @WebParam(name = "userNames", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.util.List<java.lang.String> userNames
    );

    @WebMethod
    @RequestWrapper(localName = "getCompanyHomeNodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetCompanyHomeNodeId")
    @ResponseWrapper(localName = "getCompanyHomeNodeIdResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetCompanyHomeNodeIdResponse")
    @WebResult(name = "getCompanyHomeNodeIdReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public java.lang.String getCompanyHomeNodeId()
;

    @WebMethod
    @RequestWrapper(localName = "hasContent", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.HasContent")
    @ResponseWrapper(localName = "hasContentResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.HasContentResponse")
    @WebResult(name = "hasContentReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public boolean hasContent(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId,
        @WebParam(name = "contentProp", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String contentProp
    );

    @WebMethod
    @RequestWrapper(localName = "hasPermissionsSimple", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.HasPermissionsSimple")
    @ResponseWrapper(localName = "hasPermissionsSimpleResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.HasPermissionsSimpleResponse")
    @WebResult(name = "hasPermissionsSimpleReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public boolean hasPermissionsSimple(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId,
        @WebParam(name = "permissions", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.util.List<java.lang.String> permissions
    );

    @WebMethod
    @RequestWrapper(localName = "createShare", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.CreateShare")
    @ResponseWrapper(localName = "createShareResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.CreateShareResponse")
    public void createShare(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId,
        @WebParam(name = "emails", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.util.List<java.lang.String> emails,
        @WebParam(name = "expiryDate", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        long expiryDate
    );

    @WebMethod
    @RequestWrapper(localName = "hasToolPermission", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.HasToolPermission")
    @ResponseWrapper(localName = "hasToolPermissionResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.HasToolPermissionResponse")
    @WebResult(name = "hasToolPermissionReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public boolean hasToolPermission(

        @WebParam(name = "toolPermission", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String toolPermission
    );

    @WebMethod
    @RequestWrapper(localName = "getChild", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetChild")
    @ResponseWrapper(localName = "getChildResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetChildResponse")
    @WebResult(name = "getChildReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public org.apache.xml.xml_soap.Map getChild(

        @WebParam(name = "parentId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String parentId,
        @WebParam(name = "type", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String type,
        @WebParam(name = "property", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String property,
        @WebParam(name = "value", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String value
    );

    @WebMethod
    @RequestWrapper(localName = "getPermissions", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetPermissions")
    @ResponseWrapper(localName = "getPermissionsResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetPermissionsResponse")
    @WebResult(name = "getPermissionsReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public org.edu_sharing.repository.client.rpc.ACL getPermissions(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId
    );

    @WebMethod
    @RequestWrapper(localName = "getProperties", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetProperties")
    @ResponseWrapper(localName = "getPropertiesResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetPropertiesResponse")
    @WebResult(name = "getPropertiesReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public org.apache.xml.xml_soap.Map getProperties(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId
    );

    @WebMethod
    @RequestWrapper(localName = "removeAspect", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.RemoveAspect")
    @ResponseWrapper(localName = "removeAspectResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.RemoveAspectResponse")
    public void removeAspect(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId,
        @WebParam(name = "aspect", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String aspect
    );

    @WebMethod
    @RequestWrapper(localName = "setUserDetails", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.SetUserDetails")
    @ResponseWrapper(localName = "setUserDetailsResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.SetUserDetailsResponse")
    public void setUserDetails(

        @WebParam(name = "userDetails", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.util.List<org.edu_sharing.webservices.alfresco.extension.UserDetails> userDetails
    );

    @WebMethod
    @RequestWrapper(localName = "getGroupFolderId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetGroupFolderId")
    @ResponseWrapper(localName = "getGroupFolderIdResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetGroupFolderIdResponse")
    @WebResult(name = "getGroupFolderIdReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public java.lang.String getGroupFolderId()
;

    @WebMethod
    @RequestWrapper(localName = "guessMimetype", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GuessMimetype")
    @ResponseWrapper(localName = "guessMimetypeResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GuessMimetypeResponse")
    @WebResult(name = "guessMimetypeReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public java.lang.String guessMimetype(

        @WebParam(name = "filename", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String filename
    );

    @WebMethod
    @RequestWrapper(localName = "removeAssociation", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.RemoveAssociation")
    @ResponseWrapper(localName = "removeAssociationResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.RemoveAssociationResponse")
    public void removeAssociation(

        @WebParam(name = "fromID", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String fromID,
        @WebParam(name = "toID", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String toID,
        @WebParam(name = "association", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String association
    );

    @WebMethod
    @RequestWrapper(localName = "getChildrenByAssociation", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetChildrenByAssociation")
    @ResponseWrapper(localName = "getChildrenByAssociationResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetChildrenByAssociationResponse")
    @WebResult(name = "getChildrenByAssociationReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public org.apache.xml.xml_soap.Map getChildrenByAssociation(

        @WebParam(name = "storeString", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String storeString,
        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId,
        @WebParam(name = "association", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String association
    );

    @WebMethod
    @RequestWrapper(localName = "validateTicket", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.ValidateTicket")
    @ResponseWrapper(localName = "validateTicketResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.ValidateTicketResponse")
    @WebResult(name = "validateTicketReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public java.lang.String validateTicket(

        @WebParam(name = "ticket", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String ticket
    );

    @WebMethod
    @RequestWrapper(localName = "hasAllPermissionsExt", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.HasAllPermissionsExt")
    @ResponseWrapper(localName = "hasAllPermissionsExtResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.HasAllPermissionsExtResponse")
    @WebResult(name = "hasAllPermissionsExtReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public org.apache.xml.xml_soap.Map hasAllPermissionsExt(

        @WebParam(name = "storeProtocol", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String storeProtocol,
        @WebParam(name = "storeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String storeId,
        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId,
        @WebParam(name = "permissions", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.util.List<java.lang.String> permissions
    );

    @WebMethod
    @RequestWrapper(localName = "isAdmin", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.IsAdmin")
    @ResponseWrapper(localName = "isAdminResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.IsAdminResponse")
    @WebResult(name = "isAdminReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public boolean isAdmin(

        @WebParam(name = "username", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String username
    );

    @WebMethod
    @RequestWrapper(localName = "revertVersion", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.RevertVersion")
    @ResponseWrapper(localName = "revertVersionResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.RevertVersionResponse")
    public void revertVersion(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId,
        @WebParam(name = "verLbl", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String verLbl
    );

    @WebMethod
    @RequestWrapper(localName = "getParents", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetParents")
    @ResponseWrapper(localName = "getParentsResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetParentsResponse")
    @WebResult(name = "getParentsReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public org.apache.xml.xml_soap.Map getParents(

        @WebParam(name = "nodeID", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeID,
        @WebParam(name = "primary", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        boolean primary
    );

    @WebMethod
    @RequestWrapper(localName = "getAssociationNodeIds", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetAssociationNodeIds")
    @ResponseWrapper(localName = "getAssociationNodeIdsResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetAssociationNodeIdsResponse")
    @WebResult(name = "getAssociationNodeIdsReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public java.util.List<java.lang.String> getAssociationNodeIds(

        @WebParam(name = "nodeID", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeID,
        @WebParam(name = "association", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String association
    );

    @WebMethod
    @RequestWrapper(localName = "getShares", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetShares")
    @ResponseWrapper(localName = "getSharesResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetSharesResponse")
    @WebResult(name = "getSharesReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public java.util.List<org.edu_sharing.repository.client.rpc.Share> getShares(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId
    );

    @WebMethod
    @RequestWrapper(localName = "search", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.Search")
    @ResponseWrapper(localName = "searchResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.SearchResponse")
    @WebResult(name = "searchReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public org.edu_sharing.webservices.alfresco.extension.SearchResult search(

        @WebParam(name = "searchCriterias", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.util.List<org.edu_sharing.webservices.alfresco.extension.SearchCriteria> searchCriterias,
        @WebParam(name = "metadatasetId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String metadatasetId,
        @WebParam(name = "start", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        int start,
        @WebParam(name = "nrOfResults", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        int nrOfResults,
        @WebParam(name = "facettes", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.util.List<java.lang.String> facettes
    );

    @WebMethod
    @RequestWrapper(localName = "addPermissionACEs", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.AddPermissionACEs")
    @ResponseWrapper(localName = "addPermissionACEsResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.AddPermissionACEsResponse")
    public void addPermissionACEs(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId,
        @WebParam(name = "aces", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.util.List<org.edu_sharing.repository.client.rpc.ACE> aces
    );

    @WebMethod
    @RequestWrapper(localName = "removeNode", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.RemoveNode")
    @ResponseWrapper(localName = "removeNodeResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.RemoveNodeResponse")
    public void removeNode(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId,
        @WebParam(name = "fromId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String fromId
    );

    @WebMethod
    @RequestWrapper(localName = "isSubOf", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.IsSubOf")
    @ResponseWrapper(localName = "isSubOfResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.IsSubOfResponse")
    @WebResult(name = "isSubOfReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public boolean isSubOf(

        @WebParam(name = "type", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String type,
        @WebParam(name = "parentType", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String parentType
    );

    @WebMethod
    @RequestWrapper(localName = "removePermissions", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.RemovePermissions")
    @ResponseWrapper(localName = "removePermissionsResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.RemovePermissionsResponse")
    public void removePermissions(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId,
        @WebParam(name = "_authority", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String authority,
        @WebParam(name = "_permissions", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.util.List<java.lang.String> permissions
    );

    @WebMethod
    @RequestWrapper(localName = "findUsers", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.FindUsers")
    @ResponseWrapper(localName = "findUsersResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.FindUsersResponse")
    @WebResult(name = "findUsersReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public org.edu_sharing.webservices.alfresco.extension.SearchResult findUsers(

        @WebParam(name = "searchProps", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.util.List<org.edu_sharing.webservices.alfresco.extension.KeyValue> searchProps,
        @WebParam(name = "eduGroupNodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String eduGroupNodeId,
        @WebParam(name = "from", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        int from,
        @WebParam(name = "nrOfResults", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        int nrOfResults
    );

    @WebMethod
    @RequestWrapper(localName = "executeAction", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.ExecuteAction")
    @ResponseWrapper(localName = "executeActionResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.ExecuteActionResponse")
    public void executeAction(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId,
        @WebParam(name = "actionName", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String actionName,
        @WebParam(name = "actionId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String actionId,
        @WebParam(name = "parameters", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        org.apache.xml.xml_soap.Map parameters,
        @WebParam(name = "async", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        boolean async
    );

    @WebMethod
    @RequestWrapper(localName = "findNodeByPath", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.FindNodeByPath")
    @ResponseWrapper(localName = "findNodeByPathResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.FindNodeByPathResponse")
    @WebResult(name = "findNodeByPathReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public java.lang.String findNodeByPath(

        @WebParam(name = "path", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String path
    );

    @WebMethod
    @RequestWrapper(localName = "removeGlobalAspectFromGroup", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.RemoveGlobalAspectFromGroup")
    @ResponseWrapper(localName = "removeGlobalAspectFromGroupResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.RemoveGlobalAspectFromGroupResponse")
    public void removeGlobalAspectFromGroup(

        @WebParam(name = "groupNodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String groupNodeId
    );

    @WebMethod
    @RequestWrapper(localName = "deleteGroup", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.DeleteGroup")
    @ResponseWrapper(localName = "deleteGroupResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.DeleteGroupResponse")
    public void deleteGroup(

        @WebParam(name = "groupNames", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.util.List<java.lang.String> groupNames
    );

    @WebMethod
    @RequestWrapper(localName = "getAspects", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetAspects")
    @ResponseWrapper(localName = "getAspectsResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetAspectsResponse")
    @WebResult(name = "getAspectsReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public java.util.List<java.lang.String> getAspects(

        @WebParam(name = "storeProtocol", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String storeProtocol,
        @WebParam(name = "storeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String storeId,
        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId
    );

    @WebMethod
    @RequestWrapper(localName = "getGroupNames", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetGroupNames")
    @ResponseWrapper(localName = "getGroupNamesResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetGroupNamesResponse")
    @WebResult(name = "getGroupNamesReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public java.util.List<java.lang.String> getGroupNames()
;

    @WebMethod
    @RequestWrapper(localName = "createNodeAtomicValues", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.CreateNodeAtomicValues")
    @ResponseWrapper(localName = "createNodeAtomicValuesResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.CreateNodeAtomicValuesResponse")
    @WebResult(name = "createNodeAtomicValuesReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public java.lang.String createNodeAtomicValues(

        @WebParam(name = "parentID", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String parentID,
        @WebParam(name = "nodeTypeString", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeTypeString,
        @WebParam(name = "childAssociation", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String childAssociation,
        @WebParam(name = "props", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        org.apache.xml.xml_soap.Map props
    );

    @WebMethod
    @RequestWrapper(localName = "removeAllMemberships", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.RemoveAllMemberships")
    @ResponseWrapper(localName = "removeAllMembershipsResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.RemoveAllMembershipsResponse")
    public void removeAllMemberships(

        @WebParam(name = "groupNames", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.util.List<java.lang.String> groupNames
    );

    @WebMethod
    @RequestWrapper(localName = "copyNode", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.CopyNode")
    @ResponseWrapper(localName = "copyNodeResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.CopyNodeResponse")
    public void copyNode(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId,
        @WebParam(name = "toNodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String toNodeId,
        @WebParam(name = "copyChildren", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        boolean copyChildren
    );

    @WebMethod
    @RequestWrapper(localName = "getGroupDetails", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetGroupDetails")
    @ResponseWrapper(localName = "getGroupDetailsResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetGroupDetailsResponse")
    @WebResult(name = "getGroupDetailsReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public java.util.List<org.edu_sharing.webservices.alfresco.extension.GroupDetails> getGroupDetails(

        @WebParam(name = "groupNames", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.util.List<java.lang.String> groupNames
    );

    @WebMethod
    @RequestWrapper(localName = "getMemberships", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetMemberships")
    @ResponseWrapper(localName = "getMembershipsResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetMembershipsResponse")
    @WebResult(name = "getMembershipsReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public java.util.List<java.lang.String> getMemberships(

        @WebParam(name = "groupName", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String groupName
    );

    @WebMethod
    @RequestWrapper(localName = "getChildrenByType", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetChildrenByType")
    @ResponseWrapper(localName = "getChildrenByTypeResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetChildrenByTypeResponse")
    @WebResult(name = "getChildrenByTypeReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public org.apache.xml.xml_soap.Map getChildrenByType(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId,
        @WebParam(name = "type", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String type
    );

    @WebMethod
    @RequestWrapper(localName = "writeContent", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.WriteContent")
    @ResponseWrapper(localName = "writeContentResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.WriteContentResponse")
    public void writeContent(

        @WebParam(name = "nodeID", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeID,
        @WebParam(name = "content", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        byte[] content,
        @WebParam(name = "mimetype", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String mimetype,
        @WebParam(name = "encoding", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String encoding,
        @WebParam(name = "property", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String property
    );

    @WebMethod
    @RequestWrapper(localName = "findGroups", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.FindGroups")
    @ResponseWrapper(localName = "findGroupsResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.FindGroupsResponse")
    @WebResult(name = "findGroupsReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public org.edu_sharing.webservices.alfresco.extension.SearchResult findGroups(

        @WebParam(name = "searchWord", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String searchWord,
        @WebParam(name = "eduGroupNodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String eduGroupNodeId,
        @WebParam(name = "from", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        int from,
        @WebParam(name = "nrOfResults", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        int nrOfResults
    );

    @WebMethod
    @RequestWrapper(localName = "removeRelationsForNode", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.RemoveRelationsForNode")
    @ResponseWrapper(localName = "removeRelationsForNodeResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.RemoveRelationsForNodeResponse")
    public void removeRelationsForNode(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId,
        @WebParam(name = "nodeParentId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeParentId
    );

    @WebMethod
    @RequestWrapper(localName = "setUserPassword", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.SetUserPassword")
    @ResponseWrapper(localName = "setUserPasswordResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.SetUserPasswordResponse")
    public void setUserPassword(

        @WebParam(name = "userName", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String password
    );

    @WebMethod
    @RequestWrapper(localName = "getRepositoryRoot", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetRepositoryRoot")
    @ResponseWrapper(localName = "getRepositoryRootResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetRepositoryRootResponse")
    @WebResult(name = "getRepositoryRootReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public java.lang.String getRepositoryRoot()
;

    @WebMethod
    @RequestWrapper(localName = "getAssocNode", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetAssocNode")
    @ResponseWrapper(localName = "getAssocNodeResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetAssocNodeResponse")
    @WebResult(name = "getAssocNodeReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public org.apache.xml.xml_soap.Map getAssocNode(

        @WebParam(name = "nodeID", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeID,
        @WebParam(name = "association", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String association
    );

    @WebMethod
    @RequestWrapper(localName = "getUserDetails", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetUserDetails")
    @ResponseWrapper(localName = "getUserDetailsResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetUserDetailsResponse")
    @WebResult(name = "getUserDetailsReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public java.util.List<org.edu_sharing.webservices.alfresco.extension.UserDetails> getUserDetails(

        @WebParam(name = "userNames", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.util.List<java.lang.String> userNames
    );

    @WebMethod
    @RequestWrapper(localName = "searchNodeIds", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.SearchNodeIds")
    @ResponseWrapper(localName = "searchNodeIdsResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.SearchNodeIdsResponse")
    @WebResult(name = "searchNodeIdsReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public java.util.List<java.lang.String> searchNodeIds(

        @WebParam(name = "store", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String store,
        @WebParam(name = "luceneQuery", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String luceneQuery,
        @WebParam(name = "permission", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String permission
    );

    @WebMethod
    @RequestWrapper(localName = "getVersionHistory", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetVersionHistory")
    @ResponseWrapper(localName = "getVersionHistoryResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetVersionHistoryResponse")
    @WebResult(name = "getVersionHistoryReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public java.util.List<org.edu_sharing.webservices.alfresco.extension.RepositoryNode> getVersionHistory(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId
    );

    @WebMethod
    @RequestWrapper(localName = "getUserInfo", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetUserInfo")
    @ResponseWrapper(localName = "getUserInfoResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetUserInfoResponse")
    @WebResult(name = "getUserInfoReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public org.apache.xml.xml_soap.Map getUserInfo(

        @WebParam(name = "userName", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String userName
    );

    @WebMethod
    @RequestWrapper(localName = "removeMemberships", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.RemoveMemberships")
    @ResponseWrapper(localName = "removeMembershipsResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.RemoveMembershipsResponse")
    public void removeMemberships(

        @WebParam(name = "groupName", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String groupName,
        @WebParam(name = "members", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.util.List<java.lang.String> members
    );

    @WebMethod
    @RequestWrapper(localName = "getEduGroupContextOfNode", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetEduGroupContextOfNode")
    @ResponseWrapper(localName = "getEduGroupContextOfNodeResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetEduGroupContextOfNodeResponse")
    @WebResult(name = "getEduGroupContextOfNodeReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public java.util.List<org.edu_sharing.webservices.alfresco.extension.KeyValue> getEduGroupContextOfNode(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId
    );

    @WebMethod
    @RequestWrapper(localName = "getChildrenCheckPermissions", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetChildrenCheckPermissions")
    @ResponseWrapper(localName = "getChildrenCheckPermissionsResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetChildrenCheckPermissionsResponse")
    @WebResult(name = "getChildrenCheckPermissionsReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public org.apache.xml.xml_soap.Map getChildrenCheckPermissions(

        @WebParam(name = "parentID", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String parentID,
        @WebParam(name = "permissionsOnChild", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.util.List<java.lang.String> permissionsOnChild
    );

    @WebMethod
    @RequestWrapper(localName = "addMemberships", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.AddMemberships")
    @ResponseWrapper(localName = "addMembershipsResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.AddMembershipsResponse")
    public void addMemberships(

        @WebParam(name = "groupName", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String groupName,
        @WebParam(name = "members", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.util.List<java.lang.String> members
    );

    @WebMethod
    @RequestWrapper(localName = "createVersion", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.CreateVersion")
    @ResponseWrapper(localName = "createVersionResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.CreateVersionResponse")
    public void createVersion(

        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId,
        @WebParam(name = "properties", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        org.apache.xml.xml_soap.Map properties
    );

    @WebMethod
    @RequestWrapper(localName = "createChildAssociation", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.CreateChildAssociation")
    @ResponseWrapper(localName = "createChildAssociationResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.CreateChildAssociationResponse")
    public void createChildAssociation(

        @WebParam(name = "from", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String from,
        @WebParam(name = "to", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String to,
        @WebParam(name = "assocType", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String assocType,
        @WebParam(name = "assocName", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String assocName
    );

    @WebMethod
    @RequestWrapper(localName = "getChildRecursive", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetChildRecursive")
    @ResponseWrapper(localName = "getChildRecursiveResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetChildRecursiveResponse")
    @WebResult(name = "getChildRecursiveReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public org.apache.xml.xml_soap.Map getChildRecursive(

        @WebParam(name = "parentId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String parentId,
        @WebParam(name = "type", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String type,
        @WebParam(name = "props", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        org.apache.xml.xml_soap.Map props
    );

    @WebMethod
    @RequestWrapper(localName = "getProperty", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetProperty")
    @ResponseWrapper(localName = "getPropertyResponse", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.alfresco.extension.GetPropertyResponse")
    @WebResult(name = "getPropertyReturn", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
    public java.lang.String getProperty(

        @WebParam(name = "storeProtocol", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String storeProtocol,
        @WebParam(name = "storeIdentifier", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String storeIdentifier,
        @WebParam(name = "nodeId", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String nodeId,
        @WebParam(name = "property", targetNamespace = "http://extension.alfresco.webservices.edu_sharing.org")
        java.lang.String property
    );
}
