
package org.edu_sharing.webservices.shibboleth.slo;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 4.0.0-SNAPSHOT-30b8b01da0cbd72d784fbbb0710efe252293caec
 * 2022-10-11T18:45:11.164+02:00
 * Generated source version: 4.0.0-SNAPSHOT
 *
 */
public final class LogoutNotification_LogoutNotification_Client {

    private static final QName SERVICE_NAME = new QName("http://slo.shibboleth.webservices.edu_sharing.org", "LogoutNotificationService");

    private LogoutNotification_LogoutNotification_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = LogoutNotificationService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        LogoutNotificationService ss = new LogoutNotificationService(wsdlURL, SERVICE_NAME);
        LogoutNotification port = ss.getLogoutNotification();

        {
        System.out.println("Invoking logoutNotification...");
        java.util.List<java.lang.String> _logoutNotification_sessionID = null;
        org.edu_sharing.webservices.shibboleth.slo.OKType _logoutNotification__return = port.logoutNotification(_logoutNotification_sessionID);
        System.out.println("logoutNotification.result=" + _logoutNotification__return);


        }

        System.exit(0);
    }

}
