package org.edu_sharing.webservices.shibboleth.slo;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.0-SNAPSHOT-30b8b01da0cbd72d784fbbb0710efe252293caec
 * 2022-10-11T18:45:11.168+02:00
 * Generated source version: 4.0.0-SNAPSHOT
 *
 */
@WebService(targetNamespace = "http://slo.shibboleth.webservices.edu_sharing.org", name = "LogoutNotification")
@XmlSeeAlso({ObjectFactory.class})
public interface LogoutNotification {

    @WebMethod
    @RequestWrapper(localName = "logoutNotification", targetNamespace = "http://slo.shibboleth.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.shibboleth.slo.LogoutNotification_Type")
    @ResponseWrapper(localName = "logoutNotificationResponse", targetNamespace = "http://slo.shibboleth.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.shibboleth.slo.LogoutNotificationResponse")
    @WebResult(name = "logoutNotificationReturn", targetNamespace = "http://slo.shibboleth.webservices.edu_sharing.org")
    public org.edu_sharing.webservices.shibboleth.slo.OKType logoutNotification(

        @WebParam(name = "sessionID", targetNamespace = "http://slo.shibboleth.webservices.edu_sharing.org")
        java.util.List<java.lang.String> sessionID
    );
}
