package org.edu_sharing.webservices.shibboleth.slo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-04T16:42:50.353+01:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://slo.shibboleth.webservices.edu_sharing.org", name = "LogoutNotification")
@XmlSeeAlso({ObjectFactory.class})
public interface LogoutNotification {

    @WebMethod
    @RequestWrapper(localName = "logoutNotification", targetNamespace = "http://slo.shibboleth.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.shibboleth.slo.LogoutNotification_Type")
    @ResponseWrapper(localName = "logoutNotificationResponse", targetNamespace = "http://slo.shibboleth.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.shibboleth.slo.LogoutNotificationResponse")
    @WebResult(name = "logoutNotificationReturn", targetNamespace = "http://slo.shibboleth.webservices.edu_sharing.org")
    public org.edu_sharing.webservices.shibboleth.slo.OKType logoutNotification(
        @WebParam(name = "sessionID", targetNamespace = "http://slo.shibboleth.webservices.edu_sharing.org")
        java.util.List<java.lang.String> sessionID
    );
}
