
package org.edu_sharing.webservices.tracking;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-01-03T11:03:55.919+01:00
 * Generated source version: 4.0.0
 */

@WebFault(name = "fault", targetNamespace = "http://tracking.webservices.edu_sharing.org")
public class TrackingException_Exception extends Exception {

    private org.edu_sharing.webservices.tracking.TrackingException faultInfo;

    public TrackingException_Exception() {
        super();
    }

    public TrackingException_Exception(String message) {
        super(message);
    }

    public TrackingException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public TrackingException_Exception(String message, org.edu_sharing.webservices.tracking.TrackingException fault) {
        super(message);
        this.faultInfo = fault;
    }

    public TrackingException_Exception(String message, org.edu_sharing.webservices.tracking.TrackingException fault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = fault;
    }

    public org.edu_sharing.webservices.tracking.TrackingException getFaultInfo() {
        return this.faultInfo;
    }
}
