
package org.edu_sharing.webservices.tracking;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-04T16:42:50.618+01:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "fault", targetNamespace = "http://tracking.webservices.edu_sharing.org")
public class TrackingException_Exception extends Exception {

    private org.edu_sharing.webservices.tracking.TrackingException fault;

    public TrackingException_Exception() {
        super();
    }

    public TrackingException_Exception(String message) {
        super(message);
    }

    public TrackingException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public TrackingException_Exception(String message, org.edu_sharing.webservices.tracking.TrackingException fault) {
        super(message);
        this.fault = fault;
    }

    public TrackingException_Exception(String message, org.edu_sharing.webservices.tracking.TrackingException fault, java.lang.Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public org.edu_sharing.webservices.tracking.TrackingException getFaultInfo() {
        return this.fault;
    }
}
