package org.edu_sharing.webservices.tracking;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.0-SNAPSHOT-30b8b01da0cbd72d784fbbb0710efe252293caec
 * 2022-10-11T18:45:11.325+02:00
 * Generated source version: 4.0.0-SNAPSHOT
 *
 */
@WebService(targetNamespace = "http://tracking.webservices.edu_sharing.org", name = "Tracking")
@XmlSeeAlso({ObjectFactory.class})
public interface Tracking {

    @WebMethod
    @RequestWrapper(localName = "trackEvents", targetNamespace = "http://tracking.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.tracking.TrackEvents")
    @ResponseWrapper(localName = "trackEventsResponse", targetNamespace = "http://tracking.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.tracking.TrackEventsResponse")
    public void trackEvents(

        @WebParam(name = "events", targetNamespace = "http://tracking.webservices.edu_sharing.org")
        java.util.List<org.edu_sharing.webservices.tracking.TrackingItem> events
    ) throws TrackingException_Exception;

    @WebMethod
    @RequestWrapper(localName = "trackEvent", targetNamespace = "http://tracking.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.tracking.TrackEvent")
    @ResponseWrapper(localName = "trackEventResponse", targetNamespace = "http://tracking.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.tracking.TrackEventResponse")
    public void trackEvent(

        @WebParam(name = "event", targetNamespace = "http://tracking.webservices.edu_sharing.org")
        org.edu_sharing.webservices.tracking.TrackingItem event
    ) throws TrackingException_Exception;
}
