package org.edu_sharing.webservices.tracking;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.0-SNAPSHOT-30b8b01da0cbd72d784fbbb0710efe252293caec
 * 2022-10-11T18:45:11.327+02:00
 * Generated source version: 4.0.0-SNAPSHOT
 *
 */
@WebServiceClient(name = "TrackingService",
                  wsdlLocation = "classpath:wsdl/tracking.wsdl",
                  targetNamespace = "http://tracking.webservices.edu_sharing.org")
public class TrackingService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tracking.webservices.edu_sharing.org", "TrackingService");
    public final static QName Tracking = new QName("http://tracking.webservices.edu_sharing.org", "Tracking");
    static {
        URL url = TrackingService.class.getClassLoader().getResource("wsdl/tracking.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(TrackingService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/tracking.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TrackingService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TrackingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TrackingService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TrackingService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TrackingService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TrackingService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Tracking
     */
    @WebEndpoint(name = "Tracking")
    public Tracking getTracking() {
        return super.getPort(Tracking, Tracking.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Tracking
     */
    @WebEndpoint(name = "Tracking")
    public Tracking getTracking(WebServiceFeature... features) {
        return super.getPort(Tracking, Tracking.class, features);
    }

}
