
package org.edu_sharing.webservices.tracking;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.0-SNAPSHOT-30b8b01da0cbd72d784fbbb0710efe252293caec
 * 2022-10-11T18:45:11.324+02:00
 * Generated source version: 4.0.0-SNAPSHOT
 */

@WebFault(name = "fault", targetNamespace = "http://tracking.webservices.edu_sharing.org")
public class TrackingException_Exception extends Exception {

    private org.edu_sharing.webservices.tracking.TrackingException faultInfo;

    public TrackingException_Exception() {
        super();
    }

    public TrackingException_Exception(String message) {
        super(message);
    }

    public TrackingException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public TrackingException_Exception(String message, org.edu_sharing.webservices.tracking.TrackingException fault) {
        super(message);
        this.faultInfo = fault;
    }

    public TrackingException_Exception(String message, org.edu_sharing.webservices.tracking.TrackingException fault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = fault;
    }

    public org.edu_sharing.webservices.tracking.TrackingException getFaultInfo() {
        return this.faultInfo;
    }
}
