package org.edu_sharing.webservices.tracking;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-04T16:42:50.620+01:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://tracking.webservices.edu_sharing.org", name = "Tracking")
@XmlSeeAlso({ObjectFactory.class})
public interface Tracking {

    @WebMethod
    @RequestWrapper(localName = "trackEvents", targetNamespace = "http://tracking.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.tracking.TrackEvents")
    @ResponseWrapper(localName = "trackEventsResponse", targetNamespace = "http://tracking.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.tracking.TrackEventsResponse")
    public void trackEvents(
        @WebParam(name = "events", targetNamespace = "http://tracking.webservices.edu_sharing.org")
        java.util.List<org.edu_sharing.webservices.tracking.TrackingItem> events
    ) throws TrackingException_Exception;

    @WebMethod
    @RequestWrapper(localName = "trackEvent", targetNamespace = "http://tracking.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.tracking.TrackEvent")
    @ResponseWrapper(localName = "trackEventResponse", targetNamespace = "http://tracking.webservices.edu_sharing.org", className = "org.edu_sharing.webservices.tracking.TrackEventResponse")
    public void trackEvent(
        @WebParam(name = "event", targetNamespace = "http://tracking.webservices.edu_sharing.org")
        org.edu_sharing.webservices.tracking.TrackingItem event
    ) throws TrackingException_Exception;
}
