
package org.edu_sharing.webservices.tracking;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-04T16:42:50.615+01:00
 * Generated source version: 3.2.7
 *
 */
public final class Tracking_Tracking_Client {

    private static final QName SERVICE_NAME = new QName("http://tracking.webservices.edu_sharing.org", "TrackingService");

    private Tracking_Tracking_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TrackingService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        TrackingService ss = new TrackingService(wsdlURL, SERVICE_NAME);
        Tracking port = ss.getTracking();

        {
        System.out.println("Invoking trackEvents...");
        java.util.List<org.edu_sharing.webservices.tracking.TrackingItem> _trackEvents_events = null;
        try {
            port.trackEvents(_trackEvents_events);

        } catch (TrackingException_Exception e) {
            System.out.println("Expected exception: TrackingException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking trackEvent...");
        org.edu_sharing.webservices.tracking.TrackingItem _trackEvent_event = null;
        try {
            port.trackEvent(_trackEvent_event);

        } catch (TrackingException_Exception e) {
            System.out.println("Expected exception: TrackingException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
